image: golang:latest

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is mydomainperso.com, and that your repository is repos/projectname, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/mydomainperso.com/repos/projectname 
# Thus, making a symbolic link corrects this.
before_script:
    - ln -s CI_PROJECT_DIR /go/src/Citrix-NetScaler-Exporter
    - cd /go/src/Citrix-NetScaler-Exporter
    
stages:
    - test
    - build

format:
    stage: test
    script:
        - go get github.com/alecthomas/kingpin
        - go tool vet -composites=false -shadow=true *.go
        - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
        - go get github.com/alecthomas/kingpin
        # Better put this in a Makefile
        - go build -race -ldflags "-extldflags '-static'" -o Citrix-NetScaler-Exporter.exe
    artifacts:
        paths:
            - Citrix-NetScaler-Exporter.exe
        expire_in: 2 weeks
